# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '1995' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 1995

  target '1995Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '1995UITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod "AFNetworking"
pod "SDWebImage"
pod "MJExtension"

end
